grails-app/controllers/urbanfarmtrading/AdminDashboardController.groovy
package urbanfarmtrading

import grails.transaction.Transactional

@Transactional(readOnly = true)
class AdminDashboardController {

    def index() { }
}

grails-app/controllers/urbanfarmtrading/AdminFoodController.groovy
package urbanfarmtrading

import grails.transaction.Transactional
import org.springframework.dao.DataIntegrityViolationException

@Transactional(readOnly = true)
class AdminFoodController {

    static allowedMethods = [save: "POST", update: "POST", delete: "POST"]

    def index() {
        redirect(action: "list", params: params)
    }

    def list(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        [foodInstanceList: Food.list(params), foodInstanceTotal: Food.count()]
    }

    def create() {
        [foodInstance: new Food(params)]
    }

    @Transactional
    def save() {
        def foodInstance = new Food(params)
        if (!foodInstance.save(flush: true)) {
            render(view: "create", model: [foodInstance: foodInstance])
            return
        }

        flash.message = message(code: 'default.created.message', args: [message(code: 'food.label', default: 'Food'), foodInstance.id])
        redirect(action: "show", id: foodInstance.id)
    }

    def show(Long id) {
        def foodInstance = Food.get(id)
        if (!foodInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'food.label', default: 'Food'), id])
            redirect(action: "list")
            return
        }

        [foodInstance: foodInstance]
    }

    def edit(Long id) {
        def foodInstance = Food.get(id)
        if (!foodInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'food.label', default: 'Food'), id])
            redirect(action: "list")
            return
        }

        [foodInstance: foodInstance]
    }

    @Transactional
    def update(Long id, Long version) {
        def foodInstance = Food.get(id)
        if (!foodInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'food.label', default: 'Food'), id])
            redirect(action: "list")
            return
        }

        if (version != null) {
            if (foodInstance.version > version) {
                foodInstance.errors.rejectValue("version", "default.optimistic.locking.failure",
                        [message(code: 'food.label', default: 'Food')] as Object[],
                        "Another user has updated this Food while you were editing")
                render(view: "edit", model: [foodInstance: foodInstance])
                return
            }
        }

        foodInstance.properties = params

        if (!foodInstance.save(flush: true)) {
            render(view: "edit", model: [foodInstance: foodInstance])
            return
        }

        flash.message = message(code: 'default.updated.message', args: [message(code: 'food.label', default: 'Food'), foodInstance.id])
        redirect(action: "show", id: foodInstance.id)
    }

    def delete(Long id) {
        def foodInstance = Food.get(id)
        if (!foodInstance) {
            flash.message = message(code: 'default.not.found.message', args: [message(code: 'food.label', default: 'Food'), id])
            redirect(action: "list")
            return
        }

        try {
            foodInstance.delete(flush: true)
            flash.message = message(code: 'default.deleted.message', args: [message(code: 'food.label', default: 'Food'), id])
            redirect(action: "list")
        }
        catch (DataIntegrityViolationException e) {
            flash.message = message(code: 'default.not.deleted.message', args: [message(code: 'food.label', default: 'Food'), id])
            redirect(action: "show", id: id)
        }
    }
}

grails-app/controllers/urbanfarmtrading/AdminUserController.groovy
package urbanfarmtrading



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AdminUserController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond AdminUser.list(params), model:[adminUserInstanceCount: AdminUser.count()]
    }

    def show(AdminUser adminUserInstance) {
        respond adminUserInstance
    }

    def create() {
        respond new AdminUser(params)
    }

    @Transactional
    def save(AdminUser adminUserInstance) {
        if (adminUserInstance == null) {
            notFound()
            return
        }

        if (adminUserInstance.hasErrors()) {
            respond adminUserInstance.errors, view:'create'
            return
        }

        adminUserInstance.passwordToHash()

        adminUserInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'adminUserInstance.label', default: 'AdminUser'), adminUserInstance.id])
                redirect adminUserInstance
            }
            '*' { respond adminUserInstance, [status: CREATED] }
        }
    }

    def edit(AdminUser adminUserInstance) {
        respond adminUserInstance
    }

    @Transactional
    def update(AdminUser adminUserInstance) {
        if (adminUserInstance == null) {
            notFound()
            return
        }

        if (adminUserInstance.hasErrors()) {
            respond adminUserInstance.errors, view:'edit'
            return
        }

        String oldPass = adminUserInstance.password

        adminUserInstance.properties = params

        if (params.password) {
            adminUserInstance.passwordToHash()
        } else {
            adminUserInstance.password = oldPass
        }

        adminUserInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'AdminUser.label', default: 'AdminUser'), adminUserInstance.id])
                redirect adminUserInstance
            }
            '*'{ respond adminUserInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(AdminUser adminUserInstance) {

        if (adminUserInstance == null) {
            notFound()
            return
        }

        adminUserInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'AdminUser.label', default: 'AdminUser'), adminUserInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'adminUserInstance.label', default: 'AdminUser'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/controllers/urbanfarmtrading/UserProfileDashboardController.groovy
package urbanfarmtrading

import grails.converters.JSON
import grails.transaction.Transactional

import java.text.NumberFormat

import org.joda.time.DateTime

@Transactional(readOnly = true)
class UserProfileDashboardController {

    public static final LAT_LON_FORMAT = NumberFormat.getNumberInstance(new Locale('en'))

    FoodOfferService foodOfferService

    static {
        LAT_LON_FORMAT.groupingUsed = false
    }

    def index() {
        def userProfile = UserProfile.get(session.userProfile.id)

        def foodOffers = FoodOffer.executeQuery('select s from FoodOffer as s where s.availableUntil >= :now and s.userProfile.id = :userProfileId order by s.food.name asc', [userProfileId: userProfile.id, now: new DateTime().withTimeAtStartOfDay().toDate()])

         def foodDemands = FoodDemand.executeQuery('select s from FoodDemand as s where s.userProfile.id = :userProfileId order by s.food.name asc', [userProfileId: userProfile.id])

         def trades = Trade.executeQuery('select t from Trade as t where (t.engagedUser.id = :userProfile or t.engagingUser.id = :userProfile) and t.status <> :success and t.status <> :failure order by t.lastUpdated desc', [userProfile: session.userProfile.id, success: TradeStatus.SUCCESS, failure: TradeStatus.FAILURE])

        [userProfile: userProfile, latLongFormat: LAT_LON_FORMAT, foodOffers: foodOffers, foodDemands: foodDemands, trades: trades]
    }

    def listUserProfilesByLatLngBounds(double northEastLatitude, double northEastLongitude,
                                       double southWestLatitude, double southWestLongitude) {
        def hql = 'select s from UserProfile as s where s.id != :userProfileId and s.active = true and s.hasOffers = true '
        hql += " and s.latitude <= :northEastLatitude and s.latitude >= :southWestLatitude "
        hql += " and s.longitude <= :northEastLongitude and s.longitude >= :southWestLongitude "
        hql += " and s.latitude <> 0 and s.longitude <> 0 "
        hql += " order by s.rating desc "

        def hqlParams = [:]
        hqlParams.put 'userProfileId', session.userProfile.id
        hqlParams.put 'northEastLatitude', northEastLatitude
        hqlParams.put 'northEastLongitude', northEastLongitude
        hqlParams.put 'southWestLatitude', southWestLatitude
        hqlParams.put 'southWestLongitude', southWestLongitude

        def usersNearby = UserProfile.executeQuery(hql, hqlParams, [max: 30]).collect {
            [id: it.id, name: it.name, latitude: LAT_LON_FORMAT.format(it.latitude), longitude: LAT_LON_FORMAT.format(it.longitude), url: createLink(controller: 'userProfile', action: 'show', id: it.id)]
        }

        def result = [error: 0, payload: usersNearby]
        render result as JSON
    }

    def listUserProfilesWhoFulfillMyDemandByLatLngBounds(double northEastLatitude, double northEastLongitude,
                                                         double southWestLatitude, double southWestLongitude) {
        def userProfile = UserProfile.get(session.userProfile.id)

        def usersNearby = foodOfferService.whoFulfillDemand(userProfile, northEastLatitude, northEastLongitude,
                southWestLatitude, southWestLongitude).collect {
            [id: it.id, name: it.name, latitude: LAT_LON_FORMAT.format(it.latitude), longitude: LAT_LON_FORMAT.format(it.longitude), url: createLink(controller: 'userProfile', action: 'show', id: it.id)]
        }

        def result = [error: 0, payload: usersNearby]
        render result as JSON
    }
}

grails-app/views/layouts/admin.gsp
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link rel="shortcut icon" href="${resource(dir: 'images', file: 'favicon.ico')}" type="image/x-icon">

		<title>Urban Farm Trading<g:layoutTitle/></title>

        <link rel="stylesheet" href="${resource(dir: 'css', file: 'bootstrap.min.css')}">
        <script type="text/javascript" src="${resource(dir:'js', file:'jquery-1.9.1.js')}"></script>
        <script type="text/javascript" src="${resource(dir:'js', file: 'jquery.numeric.js')}"></script>
        <script src="${resource(dir: 'js', file: 'bootstrap.min.js')}"></script>

        <style>
            body {
                padding-top: 70px;
            }
        </style>

        <g:layoutHead/>
		<r:layoutResources />
	</head>
	<body>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <g:link class="navbar-brand" controller="adminDashboard">UrbanFarmTrading</g:link>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav" id="main-nav">
                        <li id="main-nav-home" class="active"><g:link controller="adminDashboard"><g:message code="home" /></g:link></li>
                        <li id="main-nav-food"><g:link controller="adminFood"><g:message code="food.plural.label" /></g:link></li>
                        <li id="main-nav-food"><g:link controller="adminUser"><g:message code="adminUser.plural.label" /></g:link></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li id="right-nav-profile" ><a href="#">${session.adminUser.name}</a></li>
                        <li><g:link controller="authentication" action="logout"><g:message code="logout"/></g:link></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container">
            <g:layoutBody/>
            <div class="footer" role="contentinfo"></div>
            <div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
        </div>
		<g:javascript library="application"/>
		<r:layoutResources />
	</body>
</html>

grails-app/views/layouts/lp.gsp
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!--> <html lang="en" class="no-js"><!--<![endif]-->
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>Urban Farm Trading<g:layoutTitle/></title>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Grow and trade food locally and get off-the-grid. A non-profit, self-sustainable community.">
        <meta name="keywords" content="urban, farm, barter, trading, organic, food">
        <meta name="author" content="Cassio Landim">
        <link rel="shortcut icon" href="${resource(dir: 'images', file: 'organic.png')}" type="image/png">

        <link rel="stylesheet" href="${resource(dir: 'css', file: 'bootstrap.min.css')}">
        <script type="text/javascript" src="${resource(dir:'js', file:'jquery-1.9.1.js')}"></script>
        <script type="text/javascript" src="${resource(dir:'js', file: 'jquery.numeric.js')}"></script>
        <script src="${resource(dir: 'js', file: 'bootstrap.min.js')}"></script>
        <style>
        /* Space out content a bit */
        body {
            padding-top: 20px;
            padding-bottom: 20px;
        }

        /* Everything but the jumbotron gets side spacing for mobile first views */
        .header,
        .marketing,
        .footer {
            padding-left: 15px;
            padding-right: 15px;
        }

        /* Custom page header */
        .header {
            border-bottom: 1px solid #e5e5e5;
        }
        /* Make the masthead heading the same height as the navigation */
        .header h3 {
            margin-top: 0;
            margin-bottom: 0;
            line-height: 40px;
            padding-bottom: 19px;
        }

        /* Custom page footer */
        .footer {
            padding-top: 19px;
            color: #777;
            border-top: 1px solid #e5e5e5;
        }

        /* Customize container */
        @media (min-width: 768px) {
            .container {
                max-width: 730px;
            }
        }
        .container-narrow > hr {
            margin: 30px 0;
        }

        /* Main marketing message and sign up button */
        .jumbotron {
            text-align: center;
            border-bottom: 1px solid #e5e5e5;
        }
        .jumbotron .btn {
            font-size: 21px;
            padding: 14px 24px;
        }

        /* Supporting marketing content */
        .marketing {
            margin: 40px 0;
        }
        .marketing p + h4 {
            margin-top: 28px;
        }

        /* Responsive: Portrait tablets and up */
        @media screen and (min-width: 768px) {
            /* Remove the padding we set earlier */
            .header,
            .marketing,
            .footer {
                padding-left: 0;
                padding-right: 0;
            }
            /* Space out the masthead */
            .header {
                margin-bottom: 30px;
            }
            /* Remove the bottom border on the jumbotron for visual effect */
            .jumbotron {
                border-bottom: 0;
            }
        }

        .form-signin {
            max-width: 390px;
            padding: 15px;
            margin: 0 auto;
        }
        .form-signin .form-signin-heading,
        .form-signin .checkbox {
            margin-bottom: 10px;
        }
        .form-signin .checkbox {
            font-weight: normal;
        }
        .form-signin .form-control {
            position: relative;
            font-size: 16px;
            height: auto;
            padding: 10px;
            -webkit-box-sizing: border-box;
            -moz-box-sizing: border-box;
            box-sizing: border-box;
        }
        .form-signin .form-control:focus {
            z-index: 2;
        }
        .form-signin input[type="text"] {
            margin-bottom: -1px;
            border-bottom-left-radius: 0;
            border-bottom-right-radius: 0;
        }
        .form-signin input[type="password"] {
            margin-bottom: 10px;
            border-top-left-radius: 0;
            border-top-right-radius: 0;
        }
        </style>
        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.stats.g.doubleclick.net/dc.js','ga');

            ga('create', 'UA-46453398-1', 'urbanfarmtrading.org');
            ga('send', 'pageview');
        </script>
        <g:layoutHead/>
		<r:layoutResources/>
	</head>
	<body>
        <div class="container">
            <div class="header">
                <ul class="nav nav-pills pull-right" id="main-nav">
                    <li id="main-nav-home" class="active"><g:link uri="/"><g:message code="home" /></g:link></li>
                    <li id="main-nav-login"><g:link controller="authentication" action="login">Login</g:link></li>
                    <li id="main-nav-contact"><g:link controller="authentication" action="contact">Contact</g:link></li>
                    <li id="main-nav-plus"><a href="https://plus.google.com/107263919515868539103" rel="publisher">Google+</a></li>
                </ul>
                <h3 class="text-muted">Urban Farm Trading</h3>
            </div>
            <g:layoutBody/>
            <div class="footer">
                <p style="font-size: xx-small"><a href="http://opensource.org"><img src="${resource(dir: 'images', file: 'osi_standard_logo.png')}" width="50px"/></a> "The OSI logo trademark is the trademark of Open Source Initiative" "This site is not affiliated with or endorsed by the Open Source Initiative"</p>
                <p style="font-size: xx-small">“Organic” symbol by Jens Tärning, from <a href="http://thenounproject.com/jens/">The Noun Project</a> collection</p>
                <p style="font-size: x-small"><a href="http://www.linkedin.com/in/cassiolandim">By Cassio Landim</a></p>
            </div>
        </div>

        <g:javascript library="application"/>
		<r:layoutResources />
	</body>
</html>

grails-app/views/layouts/main.gsp
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Grow and trade food locally and et off-the-grid.">
        <meta name="keywords" content="urban, farm, barter, trading, organic, food">
        <meta name="author" content="Cassio Landim">
        <link rel="shortcut icon" href="${resource(dir: 'images', file: 'organic.png')}" type="image/png">

		<title>Urban Farm Trading<g:layoutTitle/></title>

        <link rel="stylesheet" href="${resource(dir: 'css', file: 'bootstrap.min.css')}">
        <script type="text/javascript" src="${resource(dir:'js', file:'jquery-1.9.1.js')}"></script>
        <script type="text/javascript" src="${resource(dir:'js', file: 'jquery.numeric.js')}"></script>
        <script src="${resource(dir: 'js', file: 'bootstrap.min.js')}"></script>

        <style>
            body {
                padding-top: 70px;
            }
        </style>

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-46453398-1', 'urbanfarmtrading.org');
            ga('send', 'pageview');
        </script>

        <g:layoutHead/>
		<r:layoutResources />
	</head>
	<body>
        <div class="navbar navbar-default navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <g:link class="navbar-brand" controller="userProfileDashboard">Urban Farm Trading</g:link>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav" id="main-nav">
                        <li id="main-nav-home" class="active"><g:link controller="userProfileDashboard"><g:message code="home" /></g:link></li>
                        <li id="main-nav-trade"><g:link controller="trade"><g:message code="trade.plural.label" /></g:link></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li id="right-nav-profile" ><g:link controller="userProfile" action="show" id="${session.userProfile.id}">${session.userProfile.name}</g:link></li>
                        <li><g:link controller="authentication" action="logout"><g:message code="logout"/></g:link></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div>
        </div>

        <div class="container">
            <g:layoutBody/>
            <div class="footer" role="contentinfo"></div>
            <div id="spinner" class="spinner" style="display:none;"><g:message code="spinner.alt" default="Loading&hellip;"/></div>
        </div>
		<g:javascript library="application"/>
		<r:layoutResources />
	</body>
</html>

grails-app/views/layouts/unlogged.gsp
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="Grow and trade food locally and et off-the-grid.">
        <meta name="keywords" content="urban, farm, barter, trading, organic, food">
        <meta name="author" content="Cassio Landim">
        <link rel="shortcut icon" href="${resource(dir: 'images', file: 'organic.png')}" type="image/png">

		<title>Urban Farm Trading<g:layoutTitle/></title>

        <link rel="stylesheet" href="${resource(dir: 'css', file: 'bootstrap.min.css')}">
        <script type="text/javascript" src="${resource(dir:'js', file:'jquery-1.9.1.js')}"></script>
        <script type="text/javascript" src="${resource(dir:'js', file: 'jquery.numeric.js')}"></script>
        <script src="${resource(dir: 'js', file: 'bootstrap.min.js')}"></script>

        <style>
            body {
                padding-top: 70px;
            }
        </style>

        <script>
            (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
                (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
                    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
            })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

            ga('create', 'UA-46453398-1', 'urbanfarmtrading.org');
            ga('send', 'pageview');
        </script>

        <g:layoutHead/>
		<r:layoutResources />
	</head>
	<body>
    <div class="navbar navbar-default navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <g:link class="navbar-brand" controller="userProfileDashboard">Urban Farm Trading</g:link>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li id="right-nav-profile"><g:link controller="authentication" action="login">Login</g:link></li>
                    <li><g:link controller="authentication" action="contact">Contact</g:link></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>

    <div class="container">
        <g:layoutBody/>
        <div class="footer">
            <p style="font-size: xx-small"><a href="http://opensource.org"><img src="${resource(dir: 'images', file: 'osi_standard_logo.png')}" width="50px"/></a> "The OSI logo trademark is the trademark of Open Source Initiative" "This site is not affiliated with or endorsed by the Open Source Initiative"</p>
            <p style="font-size: xx-small">“Organic” symbol by Jens Tärning, from <a href="http://thenounproject.com/jens/">The Noun Project</a> collection</p>
            <p style="font-size: x-small"><a href="http://www.linkedin.com/in/cassiolandim">By Cassio Landim</a></p>
        </div>
    </div>
    <g:javascript library="application"/>
    <r:layoutResources />
	</body>
</html>