grails-app/domain/urbanfarmtrading/AdminUser.groovy
package urbanfarmtrading

class AdminUser {

    String name
    String login
    String password

    static constraints = {
        name blank: false, nullable: false
        login blank: false, nullable: false, unique: true
        password blank: false, password: true
    }

    public void passwordToHash() {
        password = password.encodeAsSHA256()
    }

    String toString() {
        name
    }

    static mapping = {
        sort "name"
    }
}

grails-app/controllers/urbanfarmtrading/AdminUserController.groovy
package urbanfarmtrading



import static org.springframework.http.HttpStatus.*
import grails.transaction.Transactional

@Transactional(readOnly = true)
class AdminUserController {

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        respond AdminUser.list(params), model:[adminUserInstanceCount: AdminUser.count()]
    }

    def show(AdminUser adminUserInstance) {
        respond adminUserInstance
    }

    def create() {
        respond new AdminUser(params)
    }

    @Transactional
    def save(AdminUser adminUserInstance) {
        if (adminUserInstance == null) {
            notFound()
            return
        }

        if (adminUserInstance.hasErrors()) {
            respond adminUserInstance.errors, view:'create'
            return
        }

        adminUserInstance.passwordToHash()

        adminUserInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.created.message', args: [message(code: 'adminUserInstance.label', default: 'AdminUser'), adminUserInstance.id])
                redirect adminUserInstance
            }
            '*' { respond adminUserInstance, [status: CREATED] }
        }
    }

    def edit(AdminUser adminUserInstance) {
        respond adminUserInstance
    }

    @Transactional
    def update(AdminUser adminUserInstance) {
        if (adminUserInstance == null) {
            notFound()
            return
        }

        if (adminUserInstance.hasErrors()) {
            respond adminUserInstance.errors, view:'edit'
            return
        }

        String oldPass = adminUserInstance.password

        adminUserInstance.properties = params

        if (params.password) {
            adminUserInstance.passwordToHash()
        } else {
            adminUserInstance.password = oldPass
        }

        adminUserInstance.save flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.updated.message', args: [message(code: 'AdminUser.label', default: 'AdminUser'), adminUserInstance.id])
                redirect adminUserInstance
            }
            '*'{ respond adminUserInstance, [status: OK] }
        }
    }

    @Transactional
    def delete(AdminUser adminUserInstance) {

        if (adminUserInstance == null) {
            notFound()
            return
        }

        adminUserInstance.delete flush:true

        request.withFormat {
            form {
                flash.message = message(code: 'default.deleted.message', args: [message(code: 'AdminUser.label', default: 'AdminUser'), adminUserInstance.id])
                redirect action:"index", method:"GET"
            }
            '*'{ render status: NO_CONTENT }
        }
    }

    protected void notFound() {
        request.withFormat {
            form {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'adminUserInstance.label', default: 'AdminUser'), params.id])
                redirect action: "index", method: "GET"
            }
            '*'{ render status: NOT_FOUND }
        }
    }
}

grails-app/views/adminUser/_form.gsp
<%@ page import="urbanfarmtrading.AdminUser" %>

<div class="fieldcontain ${hasErrors(bean: adminUserInstance, field: 'name', 'error')} required">
	<label for="name">
		<g:message code="adminUser.name.label" default="Name" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="name" required="" value="${adminUserInstance?.name}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: adminUserInstance, field: 'login', 'error')} required">
	<label for="login">
		<g:message code="adminUser.login.label" default="Login" />
		<span class="required-indicator">*</span>
	</label>
	<g:textField name="login" required="" value="${adminUserInstance?.login}"/>
</div>

<div class="fieldcontain ${hasErrors(bean: adminUserInstance, field: 'password', 'error')} required">
	<label for="password">
		<g:message code="adminUser.password.label" default="Password" />
		<span class="required-indicator">*</span>
	</label>
	<g:field type="password" name="password" />
</div>

grails-app/views/adminUser/create.gsp
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="admin">
		<g:set var="entityName" value="${message(code: 'adminUser.label', default: 'AdminUser')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="create-adminUser" class="content scaffold-create" role="main">
			<h1><g:message code="default.create.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${adminUserInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${adminUserInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:adminUserInstance, action:'save']" >
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:submitButton name="create" class="save" value="${message(code: 'default.button.create.label', default: 'Create')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/adminUser/edit.gsp
<%@ page import="urbanfarmtrading.AdminUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="admin">
		<g:set var="entityName" value="${message(code: 'adminUser.label', default: 'AdminUser')}" />
		<title><g:message code="default.edit.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="edit-adminUser" class="content scaffold-edit" role="main">
			<h1><g:message code="default.edit.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<g:hasErrors bean="${adminUserInstance}">
			<ul class="errors" role="alert">
				<g:eachError bean="${adminUserInstance}" var="error">
				<li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
				</g:eachError>
			</ul>
			</g:hasErrors>
			<g:form url="[resource:adminUserInstance, action:'update']" method="PUT" >
				<g:hiddenField name="version" value="${adminUserInstance?.version}" />
				<fieldset class="form">
					<g:render template="form"/>
				</fieldset>
				<fieldset class="buttons">
					<g:actionSubmit class="save" action="update" value="${message(code: 'default.button.update.label', default: 'Update')}" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>

grails-app/views/adminUser/index.gsp
<%@ page import="urbanfarmtrading.AdminUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="admin">
		<g:set var="entityName" value="${message(code: 'adminUser.label', default: 'AdminUser')}" />
		<title><g:message code="default.list.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="list-adminUser" class="content scaffold-list" role="main">
			<h1><g:message code="default.list.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
				<div class="message" role="status">${flash.message}</div>
			</g:if>
			<table>
			<thead>
					<tr>
						<g:sortableColumn property="name" title="${message(code: 'adminUser.name.label', default: 'Name')}" />
						<g:sortableColumn property="login" title="${message(code: 'adminUser.login.label', default: 'Login')}" />
					</tr>
				</thead>
				<tbody>
				<g:each in="${adminUserInstanceList}" status="i" var="adminUserInstance">
					<tr class="${(i % 2) == 0 ? 'even' : 'odd'}">
						<td><g:link action="show" id="${adminUserInstance.id}">${fieldValue(bean: adminUserInstance, field: "name")}</g:link></td>
						<td>${fieldValue(bean: adminUserInstance, field: "login")}</td>
					</tr>
				</g:each>
				</tbody>
			</table>
			<div class="pagination">
				<g:paginate total="${adminUserInstanceCount ?: 0}" />
			</div>
		</div>
	</body>
</html>

grails-app/views/adminUser/show.gsp
<%@ page import="urbanfarmtrading.AdminUser" %>
<!DOCTYPE html>
<html>
	<head>
		<meta name="layout" content="admin">
		<g:set var="entityName" value="${message(code: 'adminUser.label', default: 'AdminUser')}" />
		<title><g:message code="default.show.label" args="[entityName]" /></title>
	</head>
	<body>
		<div class="nav" role="navigation">
			<ul>
				<li><a class="home" href="${createLink(uri: '/')}"><g:message code="default.home.label"/></a></li>
				<li><g:link class="list" action="index"><g:message code="default.list.label" args="[entityName]" /></g:link></li>
				<li><g:link class="create" action="create"><g:message code="default.new.label" args="[entityName]" /></g:link></li>
			</ul>
		</div>
		<div id="show-adminUser" class="content scaffold-show" role="main">
			<h1><g:message code="default.show.label" args="[entityName]" /></h1>
			<g:if test="${flash.message}">
			<div class="message" role="status">${flash.message}</div>
			</g:if>
			<ol class="property-list adminUser">
				<li class="fieldcontain">
					<span id="name-label" class="property-label"><g:message code="adminUser.name.label" default="Name" /></span>
                    <span class="property-value" aria-labelledby="name-label"><g:fieldValue bean="${adminUserInstance}" field="name"/></span>
				</li>
				<li class="fieldcontain">
					<span id="login-label" class="property-label"><g:message code="adminUser.login.label" default="Login" /></span>
                    <span class="property-value" aria-labelledby="login-label"><g:fieldValue bean="${adminUserInstance}" field="login"/></span>
				</li>
			</ol>
			<g:form url="[resource:adminUserInstance, action:'delete']" method="DELETE">
				<fieldset class="buttons">
					<g:link class="edit" action="edit" resource="${adminUserInstance}"><g:message code="default.button.edit.label" default="Edit" /></g:link>
					<g:actionSubmit class="delete" action="delete" value="${message(code: 'default.button.delete.label', default: 'Delete')}" onclick="return confirm('${message(code: 'default.button.delete.confirm.message', default: 'Are you sure?')}');" />
				</fieldset>
			</g:form>
		</div>
	</body>
</html>