grails-app/domain/urbanfarmtrading/UserProfile.groovy
package urbanfarmtrading

class UserProfile {

    def grailsApplication

    String name
    String email
    String password
    String photoFilename
    String activationCode
    String changePasswordCode
    Boolean active = true
    Boolean hasOffers = false
    Boolean emailConfirmed = false
    Double latitude = 0D
    Double longitude = 0D
    Float rating = 3F
    Long ratingCount = 0L
    String address

    static constraints = {
        name nullable: false, blank: false, unique: true, maxSize: 250
        email blank: false, email: true, unique: true, maxSize: 250
        address maxSize: 500
        password blank: false, password: true
        latitude nullable: true
        longitude nullable: true
        photoFilename nullable: true
        activationCode nullable: true
        changePasswordCode nullable: true
    }

    def beforeInsert() {
        activationCode = UUID.randomUUID().toString()
    }

    public void passwordToHash() {
        password = password.encodeAsSHA256()
    }

    String toString() {
        name
    }

    static mapping = {
        sort "name"
    }

    String getImgSrcBig() {
        if (photoFilename)
            return "http://${grailsApplication.config.aws.bucketName}.${grailsApplication.config.aws.domain}/userprofile/${photoFilename}_600.jpg"
        return null
    }

    String getImgSrcThumbCropped() {
        if (photoFilename)
            return "http://${grailsApplication.config.aws.bucketName}.${grailsApplication.config.aws.domain}/userprofile/${photoFilename}_300.jpg"
        return null
    }

    def updateHasOffers() {
        if (hasOffers) {
            if (!FoodOffer.countByUserProfile(this)) {
                hasOffers = false
                save(flush: true)
            }
        }
    }

    static def searchByEmailLowercase(String emailRandom) {
        if (!emailRandom) return null
        def userProfiles = UserProfile.where {
            lower(email) == emailRandom.toLowerCase()
        }.list()
        return (userProfiles && userProfiles.size() > 0 ? userProfiles.get(0) : null)
    }

    def getGravatarUrl() {
        return "http://www.gravatar.com/avatar/${email.trim().toLowerCase().encodeAsMD5()}"
    }
}

grails-app/controllers/urbanfarmtrading/AuthenticationController.groovy
package urbanfarmtrading

import grails.transaction.Transactional

@Transactional(readOnly = true)
class AuthenticationController {

    static allowedMethods = [authenticate: "POST", sendChangePasswordLink: "POST"]

    def mailerService
    def recaptchaService

    def index() {
    }

    def login() {

    }

    def logout() {
        session.invalidate()
        redirect(action: 'index')
    }

    def authenticate() {
        session.userProfile = null

        def userProfile = UserProfile.findByEmailAndActive(params.email, true)
        if (userProfile) {
            if (params.password.encodeAsSHA256().equals(userProfile.password)) {
                session.userProfile = [id: userProfile.id, name: userProfile.name, email: userProfile.email,
                        latitude: userProfile.latitude, longitude: userProfile.longitude]
                redirect(controller: 'userProfileDashboard', action: 'index')
                return
            }
        }

        flash.message = "Ops... Seu usuário ou senha são inválidos."
        redirect(action: 'login')
    }

    def create() {
        [userProfileInstance: new UserProfile(params)]
    }

    @Transactional
    def save() {
        def userProfileInstance = new UserProfile()

        userProfileInstance.name = params.name
        userProfileInstance.latitude = params.double('latitude')
        userProfileInstance.longitude = params.double('longitude')
        userProfileInstance.email = params.email
        userProfileInstance.address = params.address
        userProfileInstance.password = params.password

        if (!params.password.equals(params.repassword)) {
            flash.message = message(code: 'wrongPassConfirmation')
            render(view: "create", model: [userProfileInstance: userProfileInstance])
            return
        }

        if (!recaptchaService.verifyAnswer(session, request.getRemoteAddr(), params)) {
            flash.message = message(code: 'wrongCaptcha')
            render(view: "create", model: [userProfileInstance: userProfileInstance])
            return
        }

        userProfileInstance.passwordToHash()

        if (!userProfileInstance.save(flush: true)) {
            render(view: "create", model: [userProfileInstance: userProfileInstance])
            return
        }

        recaptchaService.cleanUp(session)

        def serverUrl = grailsApplication.config.grails.serverURL
        if (!serverUrl)
            serverUrl = 'http://localhost:8080'

        def activationLink = serverUrl + createLink([controller: 'authentication', action: 'validateEmailConfirmationCode', params: [email: userProfileInstance.email, activationCode: userProfileInstance.activationCode]])

        Thread.start {
            mailerService.sendEmailConfirmationCode(userProfileInstance, activationLink)
        }

        session.userProfile = [id: userProfileInstance.id, name: userProfileInstance.name, email: userProfileInstance.email, latitude: userProfileInstance.latitude, longitude: userProfileInstance.longitude]

        redirect(controller: 'userProfileDashboard', action: 'index')
    }

    @Transactional
    def validateEmailConfirmationCode() {
        if (!params.activationCode || !params.email) {
            redirect(action: 'index')
            return
        }

        def userProfileInstance = UserProfile.searchByEmailLowercase(params.email)
        if (userProfileInstance != null && userProfileInstance.activationCode != null && userProfileInstance.activationCode.equals(params.activationCode)) {
            userProfileInstance.activationCode = null
            userProfileInstance.emailConfirmed = true

            userProfileInstance.save(flush: true)

            flash.message = 'Email confirmado com sucesso'

            session.userProfile = [id: userProfileInstance.id, name: userProfileInstance.name, email: userProfileInstance.email, latitude: userProfileInstance.latitude, longitude: userProfileInstance.longitude]

            redirect(controller: 'userProfileDashboard', action: 'index')
        } else {
            flash.message = 'Código de confirmação inválido'
            redirect(action: 'index')
        }
    }

    def askForChangePasswordLink() {
    }

    @Transactional
    def sendChangePasswordLink() {
        def userProfileInstance = UserProfile.searchByEmailLowercase(params.email)
        if (userProfileInstance != null) {
            userProfileInstance.changePasswordCode = UUID.randomUUID().toString()
            userProfileInstance.save(flush: true)

            def serverUrl = grailsApplication.config.grails.serverURL
            if (!serverUrl)
                serverUrl = 'http://localhost:8080'

            def changePasswordLink = serverUrl + createLink([controller: 'authentication', action: 'changePasswordWithLink', params: [email: userProfileInstance.email, changePasswordCode: userProfileInstance.changePasswordCode]])

            Thread.start {
                mailerService.sendChangePasswordLink(userProfileInstance, changePasswordLink)
            }

            flash.message = "Um email lhe foi enviado com um link para que possa alterar sua senha"
        } else {
            flash.message = "Email inválido"
        }
        redirect(action: 'askForChangePasswordLink')
    }

    def changePasswordWithLink() {
        if (params.changePasswordCode == null || params.email == null) {
            redirect(action: 'index')
            return
        }

        def userProfileInstance = UserProfile.searchByEmailLowercase(params.email)
        if (userProfileInstance == null || userProfileInstance.changePasswordCode == null || !userProfileInstance.changePasswordCode.equals(params.changePasswordCode)) {
            flash.message = 'Solicitação de alteração de senha inválida'
            redirect(action: 'index')
            return
        }

        [userProfileInstance: userProfileInstance, changePasswordCode: params.changePasswordCode]
    }

    @Transactional
    def saveNewPassword() {
        if (!params.changePasswordCode) {
            redirect(action: 'index')
            return
        }

        def userProfileInstance = UserProfile.searchByEmailLowercase(params.email)
        if (userProfileInstance != null && userProfileInstance.changePasswordCode != null && userProfileInstance.changePasswordCode.equals(params.changePasswordCode) && params.password) {
            userProfileInstance.password = params.password
            userProfileInstance.changePasswordCode = null
            userProfileInstance.passwordToHash()

            if (!userProfileInstance.save(flush: true)) {
                render(view: "changePasswordWithLink", model: [userProfileInstance: userProfileInstance, changePasswordCode: params.changePasswordCode])
                return
            }

            flash.message = 'Senha alterada com sucesso'
            redirect(action: 'index')
            return
        }

        render(view: "changePasswordWithLink", model: [userProfileInstance: userProfileInstance, changePasswordCode: params.changePasswordCode])
    }

    def contact() { }

    def sendContact() {
        if (!recaptchaService.verifyAnswer(session, request.getRemoteAddr(), params)) {
            flash.message = 'Invalid code. Try again.'
            render(view: "contact")
        } else {
            recaptchaService.cleanUp(session)
            Thread.start {
                mailerService.sendContact(params.email, params.name, params.message)
            }
            flash.message = 'Your message has been sent. We will get in touch soon!'
            redirect(action: 'index')
        }
    }
}

grails-app/controllers/urbanfarmtrading/InfoController.groovy
package urbanfarmtrading

import grails.converters.JSON

class InfoController {

    def index() {
        [latLongFormat: UserProfileDashboardController.LAT_LON_FORMAT]
    }

    def listUserProfilesByLatLngBounds(double northEastLatitude, double northEastLongitude,
                                       double southWestLatitude, double southWestLongitude) {
        def hql = 'select s from UserProfile as s where s.active = true and s.hasOffers = true '
        hql += " and s.latitude <= :northEastLatitude and s.latitude >= :southWestLatitude "
        hql += " and s.longitude <= :northEastLongitude and s.longitude >= :southWestLongitude "
        hql += " and s.latitude <> 0 and s.longitude <> 0 "
        hql += " order by s.rating desc "

        def hqlParams = [:]
        hqlParams.put 'northEastLatitude', northEastLatitude
        hqlParams.put 'northEastLongitude', northEastLongitude
        hqlParams.put 'southWestLatitude', southWestLatitude
        hqlParams.put 'southWestLongitude', southWestLongitude

        def usersNearby = UserProfile.executeQuery(hql, hqlParams, [max: 30]).collect {
            [id: it.id, name: it.name, latitude: UserProfileDashboardController.LAT_LON_FORMAT.format(it.latitude), longitude: UserProfileDashboardController.LAT_LON_FORMAT.format(it.longitude), url: createLink(controller: 'userProfile', action: 'show', id: it.id)]
        }

        def result = [error: 0, payload: usersNearby]
        render result as JSON
    }
}

grails-app/views/authentication/askForChangePasswordLink.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="lp"/>
    <style>
    .form-signin {
        max-width: 390px;
        padding: 15px;
        margin: 0 auto;
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
        margin-bottom: 10px;
    }
    .form-signin .checkbox {
        font-weight: normal;
    }
    .form-signin .form-control {
        position: relative;
        font-size: 16px;
        height: auto;
        padding: 10px;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }
    .form-signin .form-control:focus {
        z-index: 2;
    }
    .form-signin input[type="text"] {
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
        margin-bottom: 10px;
    }
    </style>
</head>
<body>
    <g:if test="${flash.message}">
        <div class="alert alert-info alert-dismissable" role="status">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            ${flash.message}
        </div>
    </g:if>

    <div class="jumbotron">
        <g:form controller="authentication" action="sendChangePasswordLink" class="form-signin">
            <input name="email" type="text" class="form-control" placeholder="${message(code: 'login.email')}" required autofocus>
            <button class="btn btn-lg btn-success btn-block" type="submit"><g:message code="requestNewPassword" /></button>
        </g:form>
    </div>
</body>
</html>

grails-app/views/authentication/changePasswordWithLink.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="lp"/>
    <title>Urban Farm Trading</title>
    <style>
    body {
        padding-top: 40px;
        padding-bottom: 40px;
        background-color: #eee;
    }
    .form-signin {
        max-width: 390px;
        padding: 15px;
        margin: 0 auto;
    }
    .form-signin .form-signin-heading,
    .form-signin .checkbox {
        margin-bottom: 10px;
    }
    .form-signin .checkbox {
        font-weight: normal;
    }
    .form-signin .form-control {
        position: relative;
        font-size: 16px;
        height: auto;
        padding: 10px;
        -webkit-box-sizing: border-box;
        -moz-box-sizing: border-box;
        box-sizing: border-box;
    }
    .form-signin .form-control:focus {
        z-index: 2;
    }
    #password {
        margin-bottom: -1px;
        border-bottom-left-radius: 0;
        border-bottom-right-radius: 0;
    }
    #confirmation {
        margin-bottom: 10px;
        border-top-left-radius: 0;
        border-top-right-radius: 0;
    }
    </style>
</head>
<body>
<div class="container">
    <g:form controller="authentication" action="saveNewPassword" class="form-signin">
        <h2 class="form-signin-heading"><img src="${resource(dir: 'images', file: 'logo.png')}" width="60px"/> Urban Farm Trading</h2>

        <g:if test="${flash.message}">
            <div class="alert alert-info alert-dismissable" role="status">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                ${flash.message}
            </div>
        </g:if>

        <g:hasErrors bean="${userProfileInstance}">
            <ul class="errors" role="alert">
                <g:eachError bean="${userProfileInstance}" var="error">
                    <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                </g:eachError>
            </ul>
        </g:hasErrors>

        <input type="hidden" name="email" value="${params.email}"/>
        <input type="hidden" name="changePasswordCode" value="${params.changePasswordCode}"/>
        <input type="password" placeholder="${message(code: 'login.newPassword')}" id="password" name="password" class="form-control" required autofocus/>
        <input type="password" placeholder="${message(code: 'login.passwordConfirmation')}" id="confirmation" name="passwordConfirmation" class="form-control" required/>
        <button class="btn btn-lg btn-success btn-block" type="submit"><g:message code="saveNewPassword" /></button>
    </g:form>
</div>
</body>
</html>

grails-app/views/authentication/contact.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="lp"/>
    <g:set var="entityName" value="${message(code: 'userProfile.label', default: 'UserProfile')}" />
    <title> - Contact</title>
    <script>
        $(document).ready(function() {
            $('#main-nav li').removeClass('active');
            $('#main-nav-contact').addClass('active');

            $('#create').click(function() {
                ga('send', 'event', 'contact', 'send');
            });
        });
    </script>
</head>
<body>
<g:if test="${flash.message}">
    <div class="alert alert-danger alert-dismissable" role="status">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        ${flash.message}
    </div>
</g:if>

<div class="jumbotron">
<g:form action="sendContact" class="form-horizontal" role="form">
    <fieldset class="form">
        <div class="form-group fieldcontain">
            <label for="name" class="col-sm-2 control-label">
                <g:message code="name.label" default="Name" />
            </label>
            <div class="col-sm-8">
                <g:textField name="name" class="form-control" value="${params.name}" maxlength="250"/>
            </div>
        </div>

        <div class="form-group fieldcontain">
            <label for="email" class="col-sm-2 control-label">
                <g:message code="email.label" />
            </label>
            <div class="col-sm-8">
                <g:textField name="email" class="form-control" value="${params.email}" maxlength="250"/>
            </div>
        </div>

        <div class="form-group fieldcontain">
            <label for="message" class="col-sm-2 control-label">
                <g:message code="message.label" />
            </label>
            <div class="col-sm-8">
                <g:textArea name="message" class="form-control" value="${params.message}" maxlength="500"/>
            </div>
        </div>

        <div class="form-group fieldcontain required">
            <label for="recaptcha" class="col-sm-2 control-label">
            </label>
            <div class="col-sm-8">
                <recaptcha:recaptcha />
            </div>
        </div>
    </fieldset>
    <fieldset class="buttons">
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <g:submitButton name="create" class="btn btn-success" value="${message(code: 'default.button.send.label', default: 'Send')}" />
            </div>
        </div>
    </fieldset>
</g:form>
</div>
</body>
</html>

grails-app/views/authentication/create.gsp
<%@ page import="urbanfarmtrading.UserProfile" %>
<!DOCTYPE html>
<html>
	<head>
        <meta name="layout" content="lp"/>
		<g:set var="entityName" value="${message(code: 'userProfile.label', default: 'UserProfile')}" />
		<title><g:message code="default.create.label" args="[entityName]" /></title>
        <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDoYE4hTspwbzPaQnkfix4OOo_ug-gDkzQ&sensor=false">
        </script>
        <script type="text/javascript">
            $(document).ready(function() {
                $('#create').click(function() {
                    ga('send', 'event', 'user', 'create');
                });
            });

            function initializeMap() {
                var mapOptions = {
                    streetViewControl: false,
                    zoom: 4
                };

                var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);

                if(navigator.geolocation) {
                    navigator.geolocation.getCurrentPosition(function(position) {
                        var pos = new google.maps.LatLng(position.coords.latitude,
                                position.coords.longitude);

                        $('#latitude').val(position.coords.latitude);
                        $('#longitude').val(position.coords.longitude);

                        map.setCenter(pos);

                        var marker = new google.maps.Marker({
                            draggable: true,
                            position: pos,
                            map: map
                        });

                        google.maps.event.addListener(marker, "dragend", function(event) {
                            var point = marker.getPosition();
                            map.panTo(point);
                            $('#latitude').val(point.lat());
                            $('#longitude').val(point.lng());
                        });
                    }, function() {
                        handleNoGeolocation(true);
                    });
                } else {
                    handleNoGeolocation(false);
                }
            }

            google.maps.event.addDomListener(window, 'load', initializeMap);

            function handleNoGeolocation(opt) {
                alert('Geolocation not supported');
            }
        </script>
	</head>
	<body>
        <g:if test="${flash.message}">
            <div class="alert alert-info alert-dismissable" role="status">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                ${flash.message}
            </div>
        </g:if>

        <g:hasErrors bean="${userProfileInstance}">
            <div class="alert alert-danger alert-dismissable" role="status">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>

                <ul class="errors" role="alert">
                    <g:eachError bean="${userProfileInstance}" var="error">
                        <li <g:if test="${error in org.springframework.validation.FieldError}">data-field-id="${error.field}"</g:if>><g:message error="${error}"/></li>
                    </g:eachError>
                </ul>
            </div>
        </g:hasErrors>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><g:message code="userProfile.dragCursorMap" /></h3>
            </div>
            <div class="panel-body">
                <div id="map-canvas" style="width: 100%; height: 300px"></div>
            </div>
        </div>

        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><g:message code="default.create.label" args="[entityName]" /></h3>
            </div>
            <div class="panel-body">
                <g:form action="save" class="form-horizontal" role="form">
                    <g:hiddenField name="latitude" value="${userProfileInstance.latitude}"/>
                    <g:hiddenField name="longitude" value="${userProfileInstance.longitude}"/>

                    <fieldset class="form">
                        <div class="form-group fieldcontain ${hasErrors(bean: userProfileInstance, field: 'name', 'error')} required">
                            <label for="name" class="col-sm-2 control-label">
                                <g:message code="userProfile.name.label" default="Name" />
                                <span class="required-indicator">*</span>
                            </label>
                            <div class="col-sm-8">
                                <g:textField name="name" class="form-control" value="${userProfileInstance?.name}" maxlength="250"/>
                            </div>
                        </div>

                        <div class="form-group fieldcontain ${hasErrors(bean: userProfileInstance, field: 'email', 'error')} required">
                            <label for="email" class="col-sm-2 control-label">
                                <g:message code="userProfile.email.label" default="E-mail" />
                                <span class="required-indicator">*</span>
                            </label>
                            <div class="col-sm-8">
                                <g:textField name="email" class="form-control" value="${userProfileInstance?.email}" maxlength="250"/>
                            </div>
                        </div>

                        <div class="form-group fieldcontain ${hasErrors(bean: userProfileInstance, field: 'address', 'error')} required">
                            <label for="address" class="col-sm-2 control-label">
                                <g:message code="userProfile.address.label" default="Address" />
                                <span class="required-indicator">*</span>
                            </label>
                            <div class="col-sm-8">
                                <g:textField name="address" class="form-control" value="${userProfileInstance?.address}" maxlength="250"/>
                            </div>
                        </div>

                        <div class="form-group fieldcontain ${hasErrors(bean: userProfileInstance, field: 'password', 'error')} required">
                            <label for="password" class="col-sm-2 control-label">
                                <g:message code="userProfile.password.label" default="Password" />
                                <span class="required-indicator">*</span>
                            </label>
                            <div class="col-sm-8">
                                <g:passwordField name="password" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group fieldcontain required">
                            <label for="password" class="col-sm-2 control-label">
                                <g:message code="userProfile.repassword.label" />
                                <span class="required-indicator">*</span>
                            </label>
                            <div class="col-sm-8">
                                <g:passwordField name="repassword" class="form-control" />
                            </div>
                        </div>

                        <div class="form-group fieldcontain ${hasErrors(bean: userProfileInstance, field: 'password', 'error')} required">
                            <label for="recaptcha" class="col-sm-2 control-label">
                            </label>
                            <div class="col-sm-8">
                                <recaptcha:recaptcha />
                            </div>
                        </div>
                    </fieldset>
                    <fieldset class="buttons">
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-8">
                                <g:submitButton name="create" class="btn btn-success" value="${message(code: 'default.button.create.label', default: 'Create')}" />
                            </div>
                        </div>
                    </fieldset>
                </g:form>
            </div>
        </div>
	</body>
</html>

grails-app/views/authentication/index.gsp
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="lp"/>
    <link rel="stylesheet" href="${resource(dir: 'css', file: 'jquery.fancybox.css')}">
    <script type="text/javascript" src="${resource(dir:'js', file:'jquery.fancybox.pack.js')}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $(".fancybox").fancybox();
            $('#big-button').click(function() {
                ga('send', 'event', 'button', 'click', 'big-button');
            });
        });
    </script>
</head>
<body>
    <a href="https://github.com/ziglee/urbanfarmtrading"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://s3.amazonaws.com/github/ribbons/forkme_right_gray_6d6d6d.png" alt="Fork me on GitHub"></a>

    <g:if test="${flash.message}">
        <div class="alert alert-info alert-dismissable" role="status">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            ${flash.message}
        </div>
    </g:if>

    <div class="jumbotron">
        <h1>Urban Farm Trading</h1>
        <p class="lead">Grow and trade food locally and get off-the-grid. A non-profit, self-sustainable community.</p>
        <p><g:link class="btn btn-lg btn-success" elementId="big-button" controller="authentication" action="create" role="button">Sign up today</g:link><g:link style="margin-left: 20px;" class="btn btn-lg btn-primary" elementId="big-button" controller="info" action="index" role="button">Check map</g:link></p>
    </div>

    <div class="row marketing">
        <div class="col-lg-6">
            <h4>Enviromental impact</h4>
            <p>Local trading requires less transportation. This generally means contributing less to sprawl, congestion, habitat loss and pollution.</p>

            <h4>By-pass taxes</h4>
            <p>It doesn't involves money, so you don't have to give satisfaction to the government about it.</p>

            <h4>By-pass regulations</h4>
            <p>A small business requires a lot of bureaucracy. Trading food is not a business so you don't have to worry about it.</p>
        </div>

        <div class="col-lg-6">
            <h4>It is sustainable</h4>
            <p>Large-scale, agribusiness-oriented food systems are bound to fail on the long term, sunk by their own unsustainability.</p>

            <h4>Economize</h4>
            <p>Without middlemen, the only cost you have is growing you own food.</p>

            <h4>Eat healthier</h4>
            <p>Smaller-scale organic agriculture produces better food, tastier, and more rich in nutrients. No GMO contaminations.</p>
        </div>
    </div>

    <div class="row">
        <div class="col-sm-6 col-md-4">
            <a class="fancybox" href="${resource(dir: 'images', file: 'screenshot_01.png')}" title="Dashboard">
                <div class="thumbnail">
                    <img src="${resource(dir: 'images', file: 'screenshot_01.png')}" data-src="holder.js/300x200" alt="...">
                    <div class="caption">
                        <h3>Dashboard</h3>
                        <p>See who is around you offering what you need.</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-sm-6 col-md-4">
            <a class="fancybox" href="${resource(dir: 'images', file: 'screenshot_02.png')}" title="Profile">
                <div class="thumbnail">
                    <img src="${resource(dir: 'images', file: 'screenshot_02.png')}" data-src="holder.js/300x200" alt="...">
                    <div class="caption">
                        <h3>Profile</h3>
                        <p>See what someone is offering, needing and his trades history with you.</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-sm-6 col-md-4">
            <a class="fancybox" href="${resource(dir: 'images', file: 'screenshot_03.png')}" title="Trade flow">
                <div class="thumbnail">
                    <img src="${resource(dir: 'images', file: 'screenshot_03.png')}" data-src="holder.js/300x200" alt="...">
                    <div class="caption">
                        <h3>Trade flow</h3>
                        <p>Take action to complete the trade and receving notifications by email.</p>
                    </div>
                </div>
            </a>
        </div>
    </div>
</body>
</html>